login: &login
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password:

development: &development
  database: cashflow
  <<: *login

test: &test
  database: berlin_test
  <<: *login

production: &production
  database: cashflow
  <<: *login
